### ISSUE TITLE
What were you thinking

### ISSUE THREAD

**Issue by Bits360** [tpd0618/touhou-pixel-dungeon-reloaded#13]
I was going to write a decent list of suggestions for rebalancing the game, playing through the game again, only to find that dismantling and wands were crippled to uselessness, and you added an effect (onigiri) that literally just kills your run with nothing you can do about it, placed both on common enemies and in a trap. Were you even thinking?

**Comment by tpd0618** [comment]
> I was going to write a decent list of suggestions for rebalancing the game, playing through the game again, only to find that dismantling and wands were crippled to uselessness, and you added an effect (onigiri) that literally just kills your run with nothing you can do about it, placed both on common enemies and in a trap. Were you even thinking?

Hi, I removed the decay trap.
