### ISSUE TITLE
transfer of my progress from playstore

### ISSUE THREAD

**Issue by IllusionMirage** [tpd0618/touhou-pixel-dungeon-reloaded#2]
Hello Dev of this wonderful game "TOUHOU-PIXEL-DUNGEON". I came from playstore and got devastated that your game is not there anymore. (i always check there every day for updates because it's one of my fave's of all time) I searched for your contacts in the playstore but sadly all is gone, and I was a bit astonished that there is only few discussions, forum or articles about this wonderful game. my desperate search for answers (you didn't give us any heads up that the game would be phased out) led me here in github to create an account (I don't know how to code nor aware of this site) but I'm glad I finally found your latest update sadly it is the final version.

as for my concern I unlocked all of the ingame characters and I was hoping you could somehow transfer my data to the latest update (unpublished) 

and if it's not possible I fully understand, I'm glad nevertheless I've seen this. thank you so much for making this wonderful fork

**Comment by tpd0618** [comment]
> Hello Dev of this wonderful game "TOUHOU-PIXEL-DUNGEON". I came from playstore and got devastated that your game is not there anymore. (i always check there every day for updates because it's one of my fave's of all time) I searched for your contacts in the playstore but sadly all is gone, and I was a bit astonished that there is only few discussions, forum or articles about this wonderful game. my desperate search for answers (you didn't give us any heads up that the game would be phased out) led me here in github to create an account (I don't know how to code nor aware of this site) but I'm glad I finally found your latest update sadly it is the final version.
> 
> as for my concern I unlocked all of the ingame characters and I was hoping you could somehow transfer my data to the latest update (unpublished)
> 
> and if it's not possible I fully understand, I'm glad nevertheless I've seen this. thank you so much for making this wonderful fork

Hi, Firstly thanks to value my game good... but

I removed the app because the app was terrible enough. Overall almost everything were bad at all, and I found lots of unknown crash logs on app stats. Talents system for extra characters were not unique, and balance were broken, and too many bugs. As sum these problems, If It was not Touhou name, this game would be ignored. You agree this, right? I insulted touhou by releasing the buggish game. That's why I removed it from PS.

Also you should know that this app is a mod of Shattered Pixel Dungeon, not original. So this app(THPD) is not awesome.

Since remake version will be different from old THPD a lot, so transfering datas won't be supported.

I hope you understand this and please wait for the remake version.

Any extra questions?

**Comment by IllusionMirage** [comment]
Hahaha i'm very much aware of it's bugs and it's quality is a bit below than usual. 

But you see in my point of view i was prepared for a whole lot of tons of updates tweaks optimization balance etc... I must say it is a bit assuming of me that i said it is awesome, but i've seen thnigs that is so ugly people thought it didn't had a chance.

I fully understand each individual choices we had to make and i'm grateful for your work, it may not look decent for you and the others but for me and the others as well we appreciate things may it be ugly or worse because it's not its final form (caterpillar).

And about name of touhou being shamed, no, it is not 

I don't even know touhou but with your game? haha i found of these wonderful genre/theme/art. 

You wouldn't know how much I've searched for a similar game with touhou in it's name I've searched for and that is all thanks to you

About the remake version 
I'll be playing it with great attention.

Don't be ashamed of your work, you did great. Don't get me wrong I'm not trying to push you to keep updating it.

Final note:
Your fork have great potential "REALLY" great potential. 

If it's not much trouble i would like to report some bugs here and maybe give out some ideas, I don't care about the credits. Looking forward for your great updates in THPD remake soon. Best of luck Godbless!

**Comment by tpd0618** [comment]
> Hahaha i'm very much aware of it's bugs and it's quality is a bit below than usual.
> 
> But you see in my point of view i was prepared for a whole lot of tons of updates tweaks optimization balance etc... I must say it is a bit assuming of me that i said it is awesome, but i've seen thnigs that is so ugly people thought it didn't had a chance.
> 
> I fully understand each individual choices we had to make and i'm grateful for your work, it may not look decent for you and the others but for me and the others as well we appreciate things may it be ugly or worse because it's not its final form (caterpillar).
> 
> And about name of touhou being shamed, no, it is not
> 
> I don't even know touhou but with your game? haha i found of these wonderful genre/theme/art.
> 
> You wouldn't know how much I've searched for a similar game with touhou in it's name I've searched for and that is all thanks to you
> 
> About the remake version I'll be playing it with great attention.
> 
> Don't be ashamed of your work, you did great. Don't get me wrong I'm not trying to push you to keep updating it.
> 
> Final note: Your fork have great potential "REALLY" great potential.
> 
> If it's not much trouble i would like to report some bugs here and maybe give out some ideas, I don't care about the credits. Looking forward for your great updates in THPD remake soon. Best of luck Godbless!

If you want to give some ideas or report bugs asap, it's better to join Evan's pixel dungeon discord. First check touhou role in version roles channel, then you can join THPD's channel. (I seldomly see touhoupixeldungeon@gmail.com this email) I'm waiting you at any time!

**Comment by tpd0618** [comment]
> Hahaha i'm very much aware of it's bugs and it's quality is a bit below than usual.
> 
> But you see in my point of view i was prepared for a whole lot of tons of updates tweaks optimization balance etc... I must say it is a bit assuming of me that i said it is awesome, but i've seen thnigs that is so ugly people thought it didn't had a chance.
> 
> I fully understand each individual choices we had to make and i'm grateful for your work, it may not look decent for you and the others but for me and the others as well we appreciate things may it be ugly or worse because it's not its final form (caterpillar).
> 
> And about name of touhou being shamed, no, it is not
> 
> I don't even know touhou but with your game? haha i found of these wonderful genre/theme/art.
> 
> You wouldn't know how much I've searched for a similar game with touhou in it's name I've searched for and that is all thanks to you
> 
> About the remake version I'll be playing it with great attention.
> 
> Don't be ashamed of your work, you did great. Don't get me wrong I'm not trying to push you to keep updating it.
> 
> Final note: Your fork have great potential "REALLY" great potential.
> 
> If it's not much trouble i would like to report some bugs here and maybe give out some ideas, I don't care about the credits. Looking forward for your great updates in THPD remake soon. Best of luck Godbless!

Note: Evan is a developer who made Shattered Pixel Dungeon. and SPD is the most popular mod from original pixel dungeon. Also you valued that my game has great potential, well I think that depend on bugless game.
