### ISSUE TITLE
Some talismans can crash the game once they're clicked with RMB (quick use in the tab) in inventory selector 

### ISSUE THREAD

**Issue by Natchy999** [tpd0618/touhou-pixel-dungeon-reloaded#21]
Title says all. There's some kind of recreation and error log below (cuz my screen resolution is trash in OBS)

https://github.com/tpd0618/touhou-pixel-dungeon-reloaded/assets/173190443/513ba135-23c4-440c-b731-6737a4e8ebcc

![image](https://github.com/tpd0618/touhou-pixel-dungeon-reloaded/assets/173190443/16af2a15-24da-4ece-b6a9-d2b672bc6189)

**Comment by tpd0618** [comment]
Hi, sorry for late answer. First, I suggest you stop playing this game
until all major bugs are fixed. Currently I and another assistant, both
were trying to find the reason of bugs, but it seems very hard to fix them
all asap. So I think it will take some time. Luckily, the assistant gets
freedom(he had exam) when next week reaches, so you have to wait until
then. Currently this game's code is so confusing. So I think I cannot solve
them all myself asap. Of course, I will deliver your bug reports to
assistant. Sorry for the inconvinence.

2024년 6월 20일 (목) 오전 5:19, ReimuNaSVO ***@***.***>님이 작성:

**Comment by Natchy999** [comment]
It seems to be fixed on the 1.2.3 version
